apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
        - name: ENV_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: log.level
        - name: ENV_MODE_DEBUG
          valueFrom:
            configMapKeyRef:
              name: nginx-configmap
              key: mode.debug
