apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  index.html: |
    Hello ConfigMap!
  lorem.txt: |
    Lorem ipsum dolor sit amet,
    consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
