---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0001
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: NFS_SERVER_IP
    path: /exports/data-0001
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0002
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: NFS_SERVER_IP
    path: /exports/data-0002
