apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: vol1
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: vol1
    configMap:
      name: myconfigmap
